### ISSUE TITLE
Ajouter un paramètre pour poser une ACL sur les répertoires nouvellement créés

### ISSUE THREAD

**Issue by raymondBourges** [EsupPortail/esup-SyncFSNX#1]

**Comment by raymondBourges** [comment]
- Se limiter à positionner l'ACL lors de la création de répertoires juste en dessous de la racine de synchronisation (pas de positionnement de cette ACL sur les sous-répertoires)
- On utilise la notion de ACL de droits locaux à ce répertoire (qui seront hérités par les sous-répertoires)
- Voir comment on positionne des ACL sur un répertoire en automation. Utiliser directement le modèle objet utilisé par automation pour définir la forme du paramètre (sérialisation JSON ?)

**Comment by raymondBourges** [comment]
http://explorer.nuxeo.org/nuxeo/site/distribution/Nuxeo%20Platform-5.6/viewOperation/Document.SetACE

**Comment by llevague** [comment]
Done in 1.1.5
